### ISSUE TITLE
Screen blank after upload - ILI948x

### ISSUE THREAD

**Issue by RKF-FKR** [funnypolynomial/LittleZone#1]
I'm running Elite Petite quite successfully on my ILI948x, but I tried the the Little Zone sketch without success.

I've defined as below on Game.h:

// Switch between Small (240x320 Touch) and Large (320x480) LCD's
//#include "Game_Small.h"
#include "Game_Large.h"

Are there any other edits that I need to make?  Thanks.

**Comment by funnypolynomial** [comment]
I'll check when I get a chance.  I know I mostly focused on the small variant, the large just came across from ElitePetite, and while I think I got it to go, it wasn't idea.  The screen size really stresses the sparse algorithm

**Comment by RKF-FKR** [comment]
Thank you very much - it would make an awesome clock - I have history with this game.  Happy to stick it on a Mega if processing power is an issue.

**Comment by funnypolynomial** [comment]
I've updated the repo, the Large option was broken, I think I was part way through removing it entirely....
But it's back, FWIW.  Just comment out the (new)  `#define LCD_SMALL` line in Game.h
It is slow.
There may also be some "glitching", some missing pixels because the SparseXL buffer hits capacity.  You could try increasing
`const int SPARSE_POOL_SIZE = 1400;`
in SparseXL a little. 

Or a **lot** if using a Mega. I guess it would then run faster too.

I don't have a Mega to try, but you would probably hit issues with my use of **port registers** in ILI948x.*

**Comment by RKF-FKR** [comment]
Thank you so much for indulging me.  I appreciate it.  
I have re-loaded the code and yes, its quite slow. Increasing _"const int SPARSE_POOL_SIZE = 1400;"_  loaded ok also but I didn't notice much difference.
 I'll grab a mega and give it a try, and I'll let you know if it runs on there.
